Risteys
=======

This directory contains the code to power the online FinRegistry-FinnGen Risteys web portal. For the data pipeline, please check the other link:../pipeline/README.md[pipeline] directory.

The project is based on the https://phoenixframework.org/[Phoenix web framework].
This framework is written in https://elixir-lang.org/[elixir], which is also used to do data pre-processing and import into the database.
The front-end interactions are using https://vuejs.org/[Vue.js].
Communication between Vue.js and the backend is done using https://hexdocs.pm/phoenix/channels.html[Phoenix Channels] (which runs on Websockets).


Setting up a development environment
------------------------------------

Requirements
~~~~~~~~~~~~

- https://elixir-lang.org/install.html[elixir]
- node.js
- PostgreSQL database


Configuration
~~~~~~~~~~~~~
Some configuration files contain secret credentials, therefore are not present in this public GitHub repository. Risteys developer can get them by requesting access to the GitLab repository "risteys/risteys_secrets". Please note, that FR_FG branch for FinRegistry-FinnGen Risteys has separate secret credentials than master branch.

Create a file *`dev_FRFG.secret.exs`* in the `config/` directory, with the following content and replacing the <VAR>:

dev_FRFG.secret.exs
[source,elixir]
----
use Mix.Config

# Configure your database
config :risteys, Risteys.Repo,
  username: "<USER>",
  password: "<PASSWORD>",
  database: "<DBNAME>",
  hostname: "<HOSTNAME>",
  pool_size: 10
----

Tips to find needed information:

* Open a psql console in a terminal by running `psql postgres` (`\q` to quit).
* List existing users by `\du`. If you don't have postrgesql user (other than superuser), create a user with the ability to create a database.
** create user: `CREATE USER <username> WITH PASSWORD <password>;`
** grant permission to create a database: `ALTER USER <username> CREATEDB;`
* get database name: `\conninfo`
* get hostname: +
  `SELECT boot_val,reset_val` +
  `FROM pg_settings` +
  `WHERE name='listen_addresses';;`


Create a file *`config.secret.exs`* in the `config/` directory, with the below content and replacing the <INSERT KEY HERE> with key with a random key given by Vincent. (For a working project, a random key can be made by using a command `mix phx.gen.secret 64`).

config.secret.exs
[source,elixir]
----
use Mix.Config

# Configures the endpoint
config :risteys, RisteysWeb.Endpoint,
  url: [host: "localhost"],
  secret_key_base: "<INSERT KEY HERE>",
  render_errors: [view: RisteysWeb.ErrorView, accepts: ~w(html json)],
  pubsub_server: Risteys.PubSub
----

First-time dependency initialization
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
From a terminal in the project root directory (i.e. `risteys_elixir`), run:

* `mix deps.get` to get the Elixir dependencies
* `mix ecto.setup` to create the DB and apply the migrations
* change directory to `assets/` and then `npm install` to install the Javascript dependencies listed in the `assets\package.json`
** if the command directs to some other file than `assets\package.json` and is not installing dependencies listed in that file, but gives an error instead, remove `node_modules` and `package-lock.json` and run again.


Running
~~~~~~~
change directory back to `risteys_elixir` and connect to the server: `mix phx.server`

You can now access Risteys from http://localhost:4000

Importing data
--------------

Once the Risteys web server is running we still need to put data there. First, if you haven't already, the various statistics displayed in Risteys need to be computed using the link:../pipeline/README.md[pipeline]. Then, you can proceed to importing this data into the Risteys database for them to be displayed in the web portal.

Scripts to import files into the Risteys database are in this current directory (`risteys_elixir`) and they should be run in that directory, for example:
`mix run import_icd9.exs <path-to-input-file>`.

Input files are listed at the beginning of `import_` files.

Import scripts should be run in this order:

1. import_icd10.exs, using:
  - <<file-medcode,FG Medcode>>

2. import_icd9.exs, using:
  - <<file-medcode,FG Medcode>>

3. import_endpoint_csv.exs, using:
  - <<file-endp-defs,FG Endpoint definitions>>
  - <<file-endp-main-tag,FG Endpoint main tag>>
  - <<file-endp-taglist,FG Endpoint tag list>>
  - <<file-icd10,ICD-10>>
  - <<file-endp-selected-core,FG Endpoint selected core>>

4. import_intermediate_counts.exs, using:
  - <<file-interm-counts,FG intermediate counts>>

5. import_ontology.exs, using:
  - <<file-ontology,Risteys ontology>>

6. import_excluded_endpoints.exs, using:
  - <<file-excluded_endp,FinRegistry excluded endpoints>>

7. import_key_figures.exs, using:
  - <<file-key-fig-FR-all,Risteys FinRegistry key figures of full population>> and `FR` as dataset argument

8. import_key_figures.exs, using:
  - <<file-key-fig-FR-index,Risteys FinRegistry key figures of index-persons>> and `FR-index` as dataset argument

9. import_key_figures.exs, using:
  - <<file-key-fig-FG,Risteys FinnGen key figures>> and `FG` as dataset argument

10. import_distributions.exs, using:
  - <<file-distrib-age-FR,Risteys FinRegistry age distributions>> and `age` and `FR` as arguments

11. import_distributions.exs, using:
  - <<file-distrib-year-FR,Risteys FinRegistry year distributions>> and `year` and `FR` as arguments

12. import_distributions.exs, using:
  - <<file-distrib-age-FG,Risteys FinnGen age distributions>> and `age` and `FG` as arguments

13. import_distributions.exs, using:
  - <<file-distrib-year-FG,Risteys Finngen year distributions>> and `year` and `FG` as arguments

14. import_stats_cumulative_incidence.exs, using:
  - <<file-cumul-inc-FR,Risteys FinRegistry cumulative incidence>> and `FR` as argument

15. import_stats_cumulative_incidence.exs, using:
  - <<file-cumul-inc-FG,Risteys FinnGen cumulative incidence>> and `FG` as argument

16. import_interactive_mortality_baseline.exs, using:
  - <<file-mortality-baseline,Risteys FinRegistry mortality baseline cumulative hazards>>

17. import_interactive_mortality_params.exs, using:
  - <<file-mortality-params,Risteys FinRegistry mortality parameters>>

18. import_mortality_counts.exs, using:
  - <<file-mortality-counts,Risteys FinRegistry mortality counts>>

19. import_correlation.exs, using:
  - <<file-corr-pheno-geno,FinnGen phenotypic + genotypic correlations>>
  - <<file-coloc-variants,FinnGen coloc variants>>

20. import_case_overlaps_fr.exs, using:
  - <<file-case-overlaps-FR, FinRegistry case overlaps>>
  
21. import_coxhr.exs, using
  - <<file-surv-FR, FinRegistry survival analysis results>>
  
22. import_genetic_correlations.exs, using
  - <<file-gen-correlations, FinnGen genetic correlations>>

File list
~~~~~~~~~

* [[file-icd10]]ICD-10
** name: `ICD10_koodistopalvelu_2015-08_26_utf8.csv`
** source: https://koodistopalvelu.kanta.fi/codeserver/pages/classification-view-page.xhtml?classificationKey=23&versionKey=58[Kela Kansallinen koodistopalvelu]

* [[file-medcode]]FinnGen medcode
** name: `finngen_R6_medcode_ref.csv`
** source: FinnGen

* [[file-endp-defs]]FinnGen endpoint definitions
** name: `finngen_R10_endpoint_core_noncore_1.0__added_omit2_myfix.csv`

* [[file-endp-main-tag]]FinnGen endpoint main tag
** name: `FINNGEN_ENDPOINTS_DF10_Final_2022-05-16.names_tagged_ordered.csv`
** source: FinnGen clinical team

* [[file-endp-taglist]]FinnGen endpoint tag list
** name: `TAGLIST_DF10.csv`
** source: FinnGen clinical team

* [[file-endp-selected-core]]FinnGen endpoint selected core
** name: `finngen_correlation_clusters_DF8.csv`
** source: FinnGen clinical team

* [[file-interm-counts]]FinnGen endpoint intermediate counts
** name: `from_THLregisterteam_intermediate_counts_finngen_endpoints_intermediate_counts_green_export_R10_v1.csv`
** source: FinnGen registry team

* [[file-ontology]]Risteys ontology
** name: `ontology_2022-08-22.json`
** source: Risteys pipeline

* [[file-excluded_endp]]FinRegistry excluded endpoints
** name: `excluded_endpoints_FR_Risteys_R10.csv`
** source: Risteys script

* [[file-key-fig-FR-all]]Risteys FinRegistry key figures, all individuals
** name: `key_figures_all_2022-10-10.csv`
** source: Risteys pipeline

* [[file-key-fig-FR-index]]Risteys FinRegistry key figures, only index-persons
** name: `key_figures_index_2022-10-10.csv`
** source: Risteys pipeline

* [[file-key-fig-FG]]Risteys FinnGen key figures
** name: `key_figures_all__fg_r10__2022-10-17.csv`
** source: Risteys pipeline

* [[file-distrib-age-FR]]Risteys FinRegistry age distributions
** name: `distribution_age_2022-10-10_with_EXALLC_EXMORE.csv`
** source: Risteys pipeline

* [[file-distrib-year-FR]]Risteys FinRegistry year distributions
** name: `distribution_year_2022-10-10.csv_with_EXALLC_EXMORE.csv`
** source: Risteys pipeline

* [[file-distrib-age-FG]]Risteys FinnGen age distributions
** name: `distribution_age__fg_r10__2022-10-17.csv`
** source: Risteys pipeline

* [[file-distrib-year-FG]]Risteys FinnGen year distributions
** name: `distribution_year__fg_r10__2022-10-17.csv`
** source: Risteys pipeline

* [[file-cumul-inc-FR]]Risteys FinRegistry cumulative incidence
** name: `cumulative_incidence_2022-10-10_with_EXALLC_EXMORE.csv`
** source: Risteys pipeline

* [[file-cumul-inc-FG]]Risteys FinnGen cumulative incidence
** name: `all__cumulative_incidence__fg_r10__2022-10-17.csv`
** source: Risteys pipeline

* [[file-mortality-baseline]]Risteys FinRegistry mortality baseline cumulative hazards
** name: `mortality_baseline_cumulative_hazard_2022-10-11_with_EXALLC_EXMORE.csv`
** source: Risteys pipeline

* [[file-mortality-params]]Risteys FinRegistry mortality parameters
** name: `mortality_params_2022-10-11_with_EXALLC_EXMORE.csv`
** source: Risteys pipeline

* [[file-mortality-counts]]Risteys FinRegistry mortality counts
** name: `mortality_counts_2022-10-11_with_EXALLC_EXMORE.csv`
** source: Risteys pipeline

* [[file-corr-pheno-geno]]FinnGen phenotypic + genotypic correlations
** name: `corr_pheno-fg-r10.0_geno-fg-r10.0_full-join__2023-01-11.csv`
** source: FinnGen correlation pipeline for the phenotypic file, merged with genotypic correlation file from FinnGen analysis team

* [[file-coloc-variants]]FinnGen coloc variants
** name: `r10.autoreport.compare.keep_cs.r2_0.8.pval_5e_8.variants.csv`
** source: FinnGen analysis team

* [[file-case-overlaps-FR]] FinRegistry case overlaps
** name: `case_overlap_2022-12-31.csv`
** source: Risteys pipeline

* [[file-surv-FR]] FinRegistry survival analysis results
** name: `surv_priority_endpoints_2022-12-25.csv`
** source: Risteys pipeline

* [[file-gen-correlations]] FinnGen genetic correlations
** name: `finngen_R10_FIN.ldsc.summary.tsv`
** source: FinnGen Green library
